# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: &name KENDRA ALLGOOD
email: kendraallgood@gmail.com
description: &description TEXTILE DESIGNER
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sjip1492.github.io" # the base hostname & protocol for your site, e.g. http://example.com
fullurl: "https://sjip1492.github.io/allgood-site/"
minimal_mistakes_skin: "contrast"
website_cred: "Sarah Jade"
website_cred_link: "https://sarahjade.ca"
# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

atom_feed:
  path : "" # blank (default) uses feed.xml

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Site Footer
footer:
  links:
    - label: ""
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kendrallgood"

after_footer_scripts:
  - "/assets/js/slick-1.8.1/slick/slick.min.js"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
